# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c180a637cb14ed60eadeb4dc704d261b"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "SNS-FBT"
handle = "sns-fbt"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_content, unauthenticated_read_product_listings, unauthenticated_read_product_tags, unauthenticated_read_product_inventory,write_products,write_orders,write_customers,write_files,read_discounts,write_draft_orders,write_inventory,write_publications"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "checkout-shiv.myshopify.com"
include_config_on_deploy = true

[[extensions]]
name = "product-offer"
type = "ui_extension"
handle = "product-offer"

  [[extensions.targeting]]
  module = "./src/Checkout.jsx"
  target = "purchase.checkout.block.render"

  [extensions.capabilities]
  api_access = true
  network_access = true
  block_progress = false

[[extensions.metafields.read]]
namespace = "custom"
key = "upsell_product_checkout"
